/*
Package verizon

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

import (
    "encoding/json"
    "fmt"
)

// NotificationGroupNameTriggerAttribute represents a NotificationGroupNameTriggerAttribute struct.
// Notification group name trigger attribute.
type NotificationGroupNameTriggerAttribute struct {
    // If present, the NotificationGroupName will be listed here.
    Key                  *string                `json:"key,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for NotificationGroupNameTriggerAttribute,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (n NotificationGroupNameTriggerAttribute) String() string {
    return fmt.Sprintf(
    	"NotificationGroupNameTriggerAttribute[Key=%v, AdditionalProperties=%v]",
    	n.Key, n.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for NotificationGroupNameTriggerAttribute.
// It customizes the JSON marshaling process for NotificationGroupNameTriggerAttribute objects.
func (n NotificationGroupNameTriggerAttribute) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(n.AdditionalProperties,
        "key"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(n.toMap())
}

// toMap converts the NotificationGroupNameTriggerAttribute object to a map representation for JSON marshaling.
func (n NotificationGroupNameTriggerAttribute) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, n.AdditionalProperties)
    if n.Key != nil {
        structMap["key"] = n.Key
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for NotificationGroupNameTriggerAttribute.
// It customizes the JSON unmarshaling process for NotificationGroupNameTriggerAttribute objects.
func (n *NotificationGroupNameTriggerAttribute) UnmarshalJSON(input []byte) error {
    var temp tempNotificationGroupNameTriggerAttribute
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "key")
    if err != nil {
    	return err
    }
    n.AdditionalProperties = additionalProperties
    
    n.Key = temp.Key
    return nil
}

// tempNotificationGroupNameTriggerAttribute is a temporary struct used for validating the fields of NotificationGroupNameTriggerAttribute.
type tempNotificationGroupNameTriggerAttribute  struct {
    Key *string `json:"key,omitempty"`
}
