/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Active, activeSchema } from './active';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray';
import { PricePlanTrigger, pricePlanTriggerSchema } from './pricePlanTrigger';
import { TriggerCategory, triggerCategorySchema } from './triggerCategory';

export interface Createtriggerchunk {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategory;
  pricePlanTrigger?: PricePlanTrigger;
  notification?: Notificationarray;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: Active;
  additionalProperties?: Record<string, unknown>;
}

export const createtriggerchunkSchema: Schema<Createtriggerchunk> = typedExpandoObject(
  {
    triggerName: ['triggerName', optional(string())],
    ecpdId: ['ecpdId', optional(string())],
    triggerCategory: ['triggerCategory', optional(triggerCategorySchema)],
    pricePlanTrigger: [
      'pricePlanTrigger',
      optional(lazy(() => pricePlanTriggerSchema)),
    ],
    notification: [
      'notification',
      optional(lazy(() => notificationarraySchema)),
    ],
    active: ['active', optional(activeSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
