/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Callback listener URL. */
export interface FotaV2CallbackRegistrationResult {
  /** Callback URL. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fotaV2CallbackRegistrationResultSchema: Schema<FotaV2CallbackRegistrationResult> = typedExpandoObject(
  { url: ['url', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
