/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { GioDeviceId, gioDeviceIdSchema } from './gioDeviceId';

export interface GetDeviceListWithProfilesRequest {
  accountName: string;
  provisioningStatusFilter?: string;
  profileStatusFilter?: string;
  carrierNameFilter?: string;
  deviceFilter?: GioDeviceId[];
}

export const getDeviceListWithProfilesRequestSchema: Schema<GetDeviceListWithProfilesRequest> = object(
  {
    accountName: ['accountName', string()],
    provisioningStatusFilter: ['provisioningStatusFilter', optional(string())],
    profileStatusFilter: ['profileStatusFilter', optional(string())],
    carrierNameFilter: ['carrierNameFilter', optional(string())],
    deviceFilter: [
      'deviceFilter',
      optional(array(lazy(() => gioDeviceIdSchema))),
    ],
  }
);
