/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { V2DeviceStatus, v2DeviceStatusSchema } from './v2DeviceStatus';

/** List of devices in a campaign. */
export interface V2CampaignDevice {
  /** Total device count. */
  totalDevice?: number;
  /** Has more report flag. */
  hasMoreData: boolean;
  /** Device identifier. */
  lastSeenDeviceId?: string;
  /** Maximum page size. */
  maxPageSize: number;
  /** List of devices with id in IMEI. */
  deviceList: V2DeviceStatus[];
  additionalProperties?: Record<string, unknown>;
}

export const v2CampaignDeviceSchema: Schema<V2CampaignDevice> = typedExpandoObject(
  {
    totalDevice: ['totalDevice', optional(number())],
    hasMoreData: ['hasMoreData', boolean()],
    lastSeenDeviceId: ['lastSeenDeviceId', optional(string())],
    maxPageSize: ['maxPageSize', number()],
    deviceList: ['deviceList', array(lazy(() => v2DeviceStatusSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
