/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Software information. */
export interface V3SoftwareInfo {
  /** Software name. */
  name: string;
  /** Software version. */
  version: string;
  /** Upgrade time. */
  upgradeTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const v3SoftwareInfoSchema: Schema<V3SoftwareInfo> = typedExpandoObject(
  {
    name: ['name', string()],
    version: ['version', string()],
    upgradeTime: ['upgradeTime', string()],
  },
  'additionalProperties',
  optional(unknown())
);
