/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  DiagnosticObservationSetting,
  diagnosticObservationSettingSchema,
} from '../models/diagnosticObservationSetting';
import { array, string } from '../schema';
import { BaseApi } from './baseApi';
import { DeviceDiagnosticsResultError } from '../errors/deviceDiagnosticsResultError';

export class DiagnosticsSettingsApi extends BaseApi {
  /**
   * This endpoint retrieves diagnostics settings synchronously.
   *
   * @param accountName Account identifier.
   * @param devices     Devices list formatted as "id, kind"
   * @return Response from the API call
   */
  async listDiagnosticsSettings(
    accountName: string,
    devices: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DiagnosticObservationSetting[]>> {
    const req = this.createRequest('GET', '/devices/settings');
    req.baseUrl('Device Diagnostics');
    const mapped = req.prepareArgs({
      accountName: [accountName, string()],
      devices: [devices, string()],
    });
    req.query('accountName', mapped.accountName);
    req.query('devices', mapped.devices);
    req.defaultToError(DeviceDiagnosticsResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vzM2MToken: true }]);
    return req.callAsJson(
      array(diagnosticObservationSettingSchema),
      requestOptions
    );
  }
}
