# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.actionobject import Actionobject
from verizon.models.filtercriteria_object_call import FiltercriteriaObjectCall
from verizon.models.rateplantype_2_condition import Rateplantype2Condition


class PricePlanTrigger(object):

    """Implementation of the 'PricePlanTrigger' model.

    Attributes:
        stand_alone (FiltercriteriaObjectCall): The model property of type
            FiltercriteriaObjectCall.
        condition (Rateplantype2Condition): The model property of type
            Rateplantype2Condition.
        action (Actionobject): The model property of type Actionobject.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "stand_alone": 'standAlone',
        "condition": 'condition',
        "action": 'action'
    }

    _optionals = [
        'stand_alone',
        'condition',
        'action',
    ]

    def __init__(self,
                 stand_alone=APIHelper.SKIP,
                 condition=APIHelper.SKIP,
                 action=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the PricePlanTrigger class"""

        # Initialize members of the class
        if stand_alone is not APIHelper.SKIP:
            self.stand_alone = stand_alone 
        if condition is not APIHelper.SKIP:
            self.condition = condition 
        if action is not APIHelper.SKIP:
            self.action = action 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        stand_alone = FiltercriteriaObjectCall.from_dictionary(dictionary.get('standAlone')) if 'standAlone' in dictionary.keys() else APIHelper.SKIP
        condition = Rateplantype2Condition.from_dictionary(dictionary.get('condition')) if 'condition' in dictionary.keys() else APIHelper.SKIP
        action = Actionobject.from_dictionary(dictionary.get('action')) if 'action' in dictionary.keys() else APIHelper.SKIP
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(stand_alone,
                   condition,
                   action,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'stand_alone={(self.stand_alone if hasattr(self, "stand_alone") else None)!r}, '
                f'condition={(self.condition if hasattr(self, "condition") else None)!r}, '
                f'action={(self.action if hasattr(self, "action") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'stand_alone={(self.stand_alone if hasattr(self, "stand_alone") else None)!s}, '
                f'condition={(self.condition if hasattr(self, "condition") else None)!s}, '
                f'action={(self.action if hasattr(self, "action") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
