/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { Cellphonenumber, cellphonenumberSchema } from '../cellphonenumber';

/** This is a container type for any-of types. */
export type NotificationarraySmsNumbers = Cellphonenumber;

export const notificationarraySmsNumbersSchema: Schema<NotificationarraySmsNumbers> = anyOf(
  [cellphonenumberSchema]
);

export namespace NotificationarraySmsNumbers {
  /**
   * Validation method to narrow down union type to Cellphonenumber type case.
   *
   * This is cellphonenumber case.
   */
  export function isCellphonenumber(value: unknown): value is Cellphonenumber {
    const validationResult = validateAndMap(value, cellphonenumberSchema);
    return validationResult.errors === false;
  }
}
