/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DeviceLocationCallback type.
 */
public class DeviceLocationCallback {
    private CallbackServiceName name;
    private String url;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DeviceLocationCallback() {
    }

    /**
     * Initialization constructor.
     * @param  name  CallbackServiceName value for name.
     * @param  url  String value for url.
     */
    public DeviceLocationCallback(
            CallbackServiceName name,
            String url) {
        this.name = name;
        this.url = url;
    }

    /**
     * Getter for Name.
     * The name of the callback service.
     * @return Returns the CallbackServiceName
     */
    @JsonGetter("name")
    public CallbackServiceName getName() {
        return name;
    }

    /**
     * Setter for Name.
     * The name of the callback service.
     * @param name Value for CallbackServiceName
     */
    @JsonSetter("name")
    public void setName(CallbackServiceName name) {
        this.name = name;
    }

    /**
     * Getter for Url.
     * The location of your callback listener.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * The location of your callback listener.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DeviceLocationCallback into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DeviceLocationCallback [" + "name=" + name + ", url=" + url
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DeviceLocationCallback.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DeviceLocationCallback.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, url);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DeviceLocationCallback}.
     */
    public static class Builder {
        private CallbackServiceName name;
        private String url;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  CallbackServiceName value for name.
         * @param  url  String value for url.
         */
        public Builder(CallbackServiceName name, String url) {
            this.name = name;
            this.url = url;
        }

        /**
         * Setter for name.
         * @param  name  CallbackServiceName value for name.
         * @return Builder
         */
        public Builder name(CallbackServiceName name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DeviceLocationCallback} object using the set fields.
         * @return {@link DeviceLocationCallback}
         */
        public DeviceLocationCallback build() {
            DeviceLocationCallback model =
                    new DeviceLocationCallback(name, url);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
