# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Search by device id.
  class DeviceIdSearch < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The string appears anywhere in the identifer.
    # @return [String]
    attr_accessor :contains

    # The identifer must start with the specified string.
    # @return [String]
    attr_accessor :startswith

    # The identifier must end with the specified string.
    # @return [String]
    attr_accessor :endswith

    # The type of the device identifier. Valid types of identifiers are:ESN
    # (decimal),EID,ICCID (up to 20 digits),IMEI (up to 16 digits),MDN,MEID
    # (hexadecimal),MSISDN.
    # @return [String]
    attr_accessor :kind

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['contains'] = 'contains'
      @_hash['startswith'] = 'startswith'
      @_hash['endswith'] = 'endswith'
      @_hash['kind'] = 'kind'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        startswith
        endswith
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(contains:, kind:, startswith: SKIP, endswith: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @contains = contains
      @startswith = startswith unless startswith == SKIP
      @endswith = endswith unless endswith == SKIP
      @kind = kind
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      contains = hash.key?('contains') ? hash['contains'] : nil
      kind = hash.key?('kind') ? hash['kind'] : nil
      startswith = hash.key?('startswith') ? hash['startswith'] : SKIP
      endswith = hash.key?('endswith') ? hash['endswith'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      DeviceIdSearch.new(contains: contains,
                         kind: kind,
                         startswith: startswith,
                         endswith: endswith,
                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} contains: #{@contains}, startswith: #{@startswith}, endswith: #{@endswith},"\
      " kind: #{@kind}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} contains: #{@contains.inspect}, startswith: #{@startswith.inspect},"\
      " endswith: #{@endswith.inspect}, kind: #{@kind.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
