# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Authenticating account ID.
  class GenerateExternalIdRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ID of the authenticating billing account, in the format
    # `{"billingaccountid":"1234567890-12345"}`.
    # @return [AccountIdentifier]
    attr_accessor :accountidentifier

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['accountidentifier'] = 'accountidentifier'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        accountidentifier
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(accountidentifier: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @accountidentifier = accountidentifier unless accountidentifier == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      accountidentifier = AccountIdentifier.from_hash(hash['accountidentifier']) if
        hash['accountidentifier']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      GenerateExternalIdRequest.new(accountidentifier: accountidentifier,
                                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} accountidentifier: #{@accountidentifier}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} accountidentifier: #{@accountidentifier.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
