# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ManagedAccountCancelResponse Model.
  class ManagedAccountCancelResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transaction identifier
    # @return [String]
    attr_accessor :txid

    # Managed account identifier
    # @return [String]
    attr_accessor :account_name

    # Primary account identifier
    # @return [String]
    attr_accessor :paccount_name

    # Service name
    # @return [ServiceName]
    attr_accessor :service_name

    # Deactivate/cancel status, Success or Fail
    # @return [String]
    attr_accessor :status

    # Detailed reason
    # @return [String]
    attr_accessor :reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['txid'] = 'txid'
      @_hash['account_name'] = 'accountName'
      @_hash['paccount_name'] = 'paccountName'
      @_hash['service_name'] = 'serviceName'
      @_hash['status'] = 'status'
      @_hash['reason'] = 'reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(txid:, account_name:, paccount_name:,
                   service_name: ServiceName::LOCATION, status:, reason:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @txid = txid
      @account_name = account_name
      @paccount_name = paccount_name
      @service_name = service_name
      @status = status
      @reason = reason
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      txid = hash.key?('txid') ? hash['txid'] : nil
      account_name = hash.key?('accountName') ? hash['accountName'] : nil
      paccount_name = hash.key?('paccountName') ? hash['paccountName'] : nil
      service_name = hash['serviceName'] ||= ServiceName::LOCATION
      status = hash.key?('status') ? hash['status'] : nil
      reason = hash.key?('reason') ? hash['reason'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ManagedAccountCancelResponse.new(txid: txid,
                                       account_name: account_name,
                                       paccount_name: paccount_name,
                                       service_name: service_name,
                                       status: status,
                                       reason: reason,
                                       additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} txid: #{@txid}, account_name: #{@account_name}, paccount_name:"\
      " #{@paccount_name}, service_name: #{@service_name}, status: #{@status}, reason: #{@reason},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} txid: #{@txid.inspect}, account_name: #{@account_name.inspect},"\
      " paccount_name: #{@paccount_name.inspect}, service_name: #{@service_name.inspect}, status:"\
      " #{@status.inspect}, reason: #{@reason.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
