# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # the reporting mode of the tilt sensor
  class Mode
    MODE = [
      # TODO: Write general description for REPORTONCHANGE
      REPORTONCHANGE = 'reportOnChange'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      MODE.include?(value)
    end
  end
end
