# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # A list of deviceId objects to use when requesting information from multiple
  # devices.
  class AccountDeviceList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # All identifiers for the device.
    # @return [Array[DeviceId]]
    attr_accessor :device_ids

    # All identifiers for the device.
    # @return [String]
    attr_accessor :ipaddress

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_ids'] = 'deviceIds'
      @_hash['ipaddress'] = 'ipAddress'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ipaddress
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_ids:, ipaddress: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @device_ids = device_ids
      @ipaddress = ipaddress unless ipaddress == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      device_ids = nil
      unless hash['deviceIds'].nil?
        device_ids = []
        hash['deviceIds'].each do |structure|
          device_ids << (DeviceId.from_hash(structure) if structure)
        end
      end

      device_ids = nil unless hash.key?('deviceIds')
      ipaddress = hash.key?('ipAddress') ? hash['ipAddress'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AccountDeviceList.new(device_ids: device_ids,
                            ipaddress: ipaddress,
                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} device_ids: #{@device_ids}, ipaddress: #{@ipaddress},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} device_ids: #{@device_ids.inspect}, ipaddress: #{@ipaddress.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
