# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Onboarding Model.
  class Onboarding < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # the IEEE EUI64 address space used to identify a device. It is supplied by
    # the device manufacturer
    # @return [String]
    attr_accessor :sensoridentifier

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sensoridentifier'] = 'sensoridentifier'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sensoridentifier
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(sensoridentifier: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @sensoridentifier = sensoridentifier unless sensoridentifier == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sensoridentifier =
        hash.key?('sensoridentifier') ? hash['sensoridentifier'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Onboarding.new(sensoridentifier: sensoridentifier,
                     additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sensoridentifier: #{@sensoridentifier}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sensoridentifier: #{@sensoridentifier.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
