<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AccountDeviceListFilter;
use VerizonLib\Models\AccountDeviceListRequest;
use VerizonLib\Models\CustomFields;
use VerizonLib\Models\DeviceId;

/**
 * Builder for model AccountDeviceListRequest
 *
 * @see AccountDeviceListRequest
 */
class AccountDeviceListRequestBuilder
{
    /**
     * @var AccountDeviceListRequest
     */
    private $instance;

    private function __construct(AccountDeviceListRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Device List Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountDeviceListRequest());
    }

    /**
     * Sets account Name field.
     *
     * @param string|null $value
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets device Id field.
     *
     * @param DeviceId|null $value
     */
    public function deviceId(?DeviceId $value): self
    {
        $this->instance->setDeviceId($value);
        return $this;
    }

    /**
     * Sets filter field.
     *
     * @param AccountDeviceListFilter|null $value
     */
    public function filter(?AccountDeviceListFilter $value): self
    {
        $this->instance->setFilter($value);
        return $this;
    }

    /**
     * Sets current State field.
     *
     * @param string|null $value
     */
    public function currentState(?string $value): self
    {
        $this->instance->setCurrentState($value);
        return $this;
    }

    /**
     * Sets custom Fields field.
     *
     * @param CustomFields[]|null $value
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets earliest field.
     *
     * @param string|null $value
     */
    public function earliest(?string $value): self
    {
        $this->instance->setEarliest($value);
        return $this;
    }

    /**
     * Sets group Name field.
     *
     * @param string|null $value
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets latest field.
     *
     * @param string|null $value
     */
    public function latest(?string $value): self
    {
        $this->instance->setLatest($value);
        return $this;
    }

    /**
     * Sets service Plan field.
     *
     * @param string|null $value
     */
    public function servicePlan(?string $value): self
    {
        $this->instance->setServicePlan($value);
        return $this;
    }

    /**
     * Sets max Number Of Devices field.
     *
     * @param int|null $value
     */
    public function maxNumberOfDevices(?int $value): self
    {
        $this->instance->setMaxNumberOfDevices($value);
        return $this;
    }

    /**
     * Sets largest Device Id Seen field.
     *
     * @param int|null $value
     */
    public function largestDeviceIdSeen(?int $value): self
    {
        $this->instance->setLargestDeviceIdSeen($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Account Device List Request object.
     */
    public function build(): AccountDeviceListRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
