<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AnomalyDetectionRequest;
use VerizonLib\Models\SensitivityParameters;

/**
 * Builder for model AnomalyDetectionRequest
 *
 * @see AnomalyDetectionRequest
 */
class AnomalyDetectionRequestBuilder
{
    /**
     * @var AnomalyDetectionRequest
     */
    private $instance;

    private function __construct(AnomalyDetectionRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Anomaly Detection Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AnomalyDetectionRequest());
    }

    /**
     * Sets account Name field.
     *
     * @param string|null $value
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets request Type field.
     *
     * @param string|null $value
     */
    public function requestType(?string $value): self
    {
        $this->instance->setRequestType($value);
        return $this;
    }

    /**
     * Sets sensitivity Parameter field.
     *
     * @param SensitivityParameters|null $value
     */
    public function sensitivityParameter(?SensitivityParameters $value): self
    {
        $this->instance->setSensitivityParameter($value);
        return $this;
    }

    /**
     * Initializes a new Anomaly Detection Request object.
     */
    public function build(): AnomalyDetectionRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
