<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\AccountDeviceList;
use VerizonLib\Models\CarrierActivateRequest;
use VerizonLib\Models\CustomFields;
use VerizonLib\Models\PlaceOfUse;

/**
 * Builder for model CarrierActivateRequest
 *
 * @see CarrierActivateRequest
 */
class CarrierActivateRequestBuilder
{
    /**
     * @var CarrierActivateRequest
     */
    private $instance;

    private function __construct(CarrierActivateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Carrier Activate Request Builder object.
     *
     * @param AccountDeviceList[] $devices
     * @param string $servicePlan
     * @param string $mdnZipCode
     */
    public static function init(array $devices, string $servicePlan, string $mdnZipCode): self
    {
        return new self(new CarrierActivateRequest($devices, $servicePlan, $mdnZipCode));
    }

    /**
     * Sets account Name field.
     *
     * @param string|null $value
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets carrier Ip Pool Name field.
     *
     * @param string|null $value
     */
    public function carrierIpPoolName(?string $value): self
    {
        $this->instance->setCarrierIpPoolName($value);
        return $this;
    }

    /**
     * Sets carrier Name field.
     *
     * @param string|null $value
     */
    public function carrierName(?string $value): self
    {
        $this->instance->setCarrierName($value);
        return $this;
    }

    /**
     * Sets cost Center Code field.
     *
     * @param string|null $value
     */
    public function costCenterCode(?string $value): self
    {
        $this->instance->setCostCenterCode($value);
        return $this;
    }

    /**
     * Sets custom Fields field.
     *
     * @param CustomFields[]|null $value
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets group Name field.
     *
     * @param string|null $value
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets lead Id field.
     *
     * @param string|null $value
     */
    public function leadId(?string $value): self
    {
        $this->instance->setLeadId($value);
        return $this;
    }

    /**
     * Sets primary Place Of Use field.
     *
     * @param PlaceOfUse|null $value
     */
    public function primaryPlaceOfUse(?PlaceOfUse $value): self
    {
        $this->instance->setPrimaryPlaceOfUse($value);
        return $this;
    }

    /**
     * Sets public Ip Restriction field.
     *
     * @param string|null $value
     */
    public function publicIpRestriction(?string $value): self
    {
        $this->instance->setPublicIpRestriction($value);
        return $this;
    }

    /**
     * Sets sku Number field.
     *
     * @param string|null $value
     */
    public function skuNumber(?string $value): self
    {
        $this->instance->setSkuNumber($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Carrier Activate Request object.
     */
    public function build(): CarrierActivateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
