<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceIdentifier;

/**
 * Builder for model DeviceIdentifier
 *
 * @see DeviceIdentifier
 */
class DeviceIdentifierBuilder
{
    /**
     * @var DeviceIdentifier
     */
    private $instance;

    private function __construct(DeviceIdentifier $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Identifier Builder object.
     *
     * @param string $kind
     * @param string $id
     */
    public static function init(string $kind, string $id): self
    {
        return new self(new DeviceIdentifier($kind, $id));
    }

    /**
     * Sets mdn field.
     *
     * @param string|null $value
     */
    public function mdn(?string $value): self
    {
        $this->instance->setMdn($value);
        return $this;
    }

    /**
     * Initializes a new Device Identifier object.
     */
    public function build(): DeviceIdentifier
    {
        return CoreHelper::clone($this->instance);
    }
}
