<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceIdSearch;

/**
 * Builder for model DeviceIdSearch
 *
 * @see DeviceIdSearch
 */
class DeviceIdSearchBuilder
{
    /**
     * @var DeviceIdSearch
     */
    private $instance;

    private function __construct(DeviceIdSearch $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Id Search Builder object.
     *
     * @param string $contains
     * @param string $kind
     */
    public static function init(string $contains, string $kind): self
    {
        return new self(new DeviceIdSearch($contains, $kind));
    }

    /**
     * Sets startswith field.
     *
     * @param string|null $value
     */
    public function startswith(?string $value): self
    {
        $this->instance->setStartswith($value);
        return $this;
    }

    /**
     * Sets endswith field.
     *
     * @param string|null $value
     */
    public function endswith(?string $value): self
    {
        $this->instance->setEndswith($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device Id Search object.
     */
    public function build(): DeviceIdSearch
    {
        return CoreHelper::clone($this->instance);
    }
}
