<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceAggregateUsageListRequest;
use VerizonLib\Models\DeviceId;
use VerizonLib\Models\Label;

/**
 * Builder for model DeviceAggregateUsageListRequest
 *
 * @see DeviceAggregateUsageListRequest
 */
class DeviceAggregateUsageListRequestBuilder
{
    /**
     * @var DeviceAggregateUsageListRequest
     */
    private $instance;

    private function __construct(DeviceAggregateUsageListRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Aggregate Usage List Request Builder object.
     *
     * @param string $startTime
     * @param string $endTime
     */
    public static function init(string $startTime, string $endTime): self
    {
        return new self(new DeviceAggregateUsageListRequest($startTime, $endTime));
    }

    /**
     * Sets device Ids field.
     *
     * @param DeviceId[]|null $value
     */
    public function deviceIds(?array $value): self
    {
        $this->instance->setDeviceIds($value);
        return $this;
    }

    /**
     * Sets account Name field.
     *
     * @param string|null $value
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets group Name field.
     *
     * @param string|null $value
     */
    public function groupName(?string $value): self
    {
        $this->instance->setGroupName($value);
        return $this;
    }

    /**
     * Sets label field.
     *
     * @param Label[]|null $value
     */
    public function label(?array $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device Aggregate Usage List Request object.
     */
    public function build(): DeviceAggregateUsageListRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
