<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DevicePropertylocation;

/**
 * Builder for model DevicePropertylocation
 *
 * @see DevicePropertylocation
 */
class DevicePropertylocationBuilder
{
    /**
     * @var DevicePropertylocation
     */
    private $instance;

    private function __construct(DevicePropertylocation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Propertylocation Builder object.
     */
    public static function init(): self
    {
        return new self(new DevicePropertylocation());
    }

    /**
     * Sets latitude field.
     *
     * @param string|null $value
     */
    public function latitude(?string $value): self
    {
        $this->instance->setLatitude($value);
        return $this;
    }

    /**
     * Sets longitude field.
     *
     * @param string|null $value
     */
    public function longitude(?string $value): self
    {
        $this->instance->setLongitude($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device Propertylocation object.
     */
    public function build(): DevicePropertylocation
    {
        return CoreHelper::clone($this->instance);
    }
}
