<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DtoGetNetworkHealthScoreResponse;
use VerizonLib\Models\DtoHealthScoreMetric;

/**
 * Builder for model DtoGetNetworkHealthScoreResponse
 *
 * @see DtoGetNetworkHealthScoreResponse
 */
class DtoGetNetworkHealthScoreResponseBuilder
{
    /**
     * @var DtoGetNetworkHealthScoreResponse
     */
    private $instance;

    private function __construct(DtoGetNetworkHealthScoreResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Dto Get Network Health Score Response Builder object.
     */
    public static function init(): self
    {
        return new self(new DtoGetNetworkHealthScoreResponse());
    }

    /**
     * Sets networksummary field.
     *
     * @param DtoHealthScoreMetric[]|null $value
     */
    public function networksummary(?array $value): self
    {
        $this->instance->setNetworksummary($value);
        return $this;
    }

    /**
     * Sets overallsummary field.
     *
     * @param DtoHealthScoreMetric[]|null $value
     */
    public function overallsummary(?array $value): self
    {
        $this->instance->setOverallsummary($value);
        return $this;
    }

    /**
     * Initializes a new Dto Get Network Health Score Response object.
     */
    public function build(): DtoGetNetworkHealthScoreResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
