<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DtoUpdateUserRequest;
use VerizonLib\Models\DtoUserDto;

/**
 * Builder for model DtoUpdateUserRequest
 *
 * @see DtoUpdateUserRequest
 */
class DtoUpdateUserRequestBuilder
{
    /**
     * @var DtoUpdateUserRequest
     */
    private $instance;

    private function __construct(DtoUpdateUserRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Dto Update User Request Builder object.
     */
    public static function init(): self
    {
        return new self(new DtoUpdateUserRequest());
    }

    /**
     * Sets accountname field.
     *
     * @param string|null $value
     */
    public function accountname(?string $value): self
    {
        $this->instance->setAccountname($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets user field.
     *
     * @param DtoUserDto|null $value
     */
    public function user(?DtoUserDto $value): self
    {
        $this->instance->setUser($value);
        return $this;
    }

    /**
     * Initializes a new Dto Update User Request object.
     */
    public function build(): DtoUpdateUserRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
