<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\FirmwareCampaign;
use VerizonLib\Models\V3TimeWindow;

/**
 * Builder for model FirmwareCampaign
 *
 * @see FirmwareCampaign
 */
class FirmwareCampaignBuilder
{
    /**
     * @var FirmwareCampaign
     */
    private $instance;

    private function __construct(FirmwareCampaign $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Firmware Campaign Builder object.
     *
     * @param string $id
     * @param string $accountName
     * @param string $firmwareFrom
     * @param string $firmwareTo
     * @param string $protocol
     * @param string $make
     * @param string $model
     * @param \DateTime $startDate
     * @param \DateTime $endDate
     * @param string $status
     */
    public static function init(
        string $id,
        string $accountName,
        string $firmwareFrom,
        string $firmwareTo,
        string $protocol,
        string $make,
        string $model,
        \DateTime $startDate,
        \DateTime $endDate,
        string $status
    ): self {
        return new self(new FirmwareCampaign(
            $id,
            $accountName,
            $firmwareFrom,
            $firmwareTo,
            $protocol,
            $make,
            $model,
            $startDate,
            $endDate,
            $status
        ));
    }

    /**
     * Sets campaign Name field.
     *
     * @param string|null $value
     */
    public function campaignName(?string $value): self
    {
        $this->instance->setCampaignName($value);
        return $this;
    }

    /**
     * Sets firmware Name field.
     *
     * @param string|null $value
     */
    public function firmwareName(?string $value): self
    {
        $this->instance->setFirmwareName($value);
        return $this;
    }

    /**
     * Sets campaign Time Window List field.
     *
     * @param V3TimeWindow[]|null $value
     */
    public function campaignTimeWindowList(?array $value): self
    {
        $this->instance->setCampaignTimeWindowList($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Firmware Campaign object.
     */
    public function build(): FirmwareCampaign
    {
        return CoreHelper::clone($this->instance);
    }
}
