<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\LicenseDeviceId;
use VerizonLib\Models\LicenseDeviceList;

/**
 * Builder for model LicenseDeviceList
 *
 * @see LicenseDeviceList
 */
class LicenseDeviceListBuilder
{
    /**
     * @var LicenseDeviceList
     */
    private $instance;

    private function __construct(LicenseDeviceList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new License Device List Builder object.
     */
    public static function init(): self
    {
        return new self(new LicenseDeviceList());
    }

    /**
     * Sets device Ids field.
     *
     * @param LicenseDeviceId[]|null $value
     */
    public function deviceIds(?array $value): self
    {
        $this->instance->setDeviceIds($value);
        return $this;
    }

    /**
     * Sets ip Address field.
     *
     * @param string|null $value
     */
    public function ipaddress(?string $value): self
    {
        $this->instance->setIpaddress($value);
        return $this;
    }

    /**
     * Initializes a new License Device List object.
     */
    public function build(): LicenseDeviceList
    {
        return CoreHelper::clone($this->instance);
    }
}
