<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\MecPerformanceQueryResult;

/**
 * Builder for model MecPerformanceQueryResult
 *
 * @see MecPerformanceQueryResult
 */
class MecPerformanceQueryResultBuilder
{
    /**
     * @var MecPerformanceQueryResult
     */
    private $instance;

    private function __construct(MecPerformanceQueryResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Mec Performance Query Result Builder object.
     */
    public static function init(): self
    {
        return new self(new MecPerformanceQueryResult());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param array<string|null>|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Mec Performance Query Result object.
     */
    public function build(): MecPerformanceQueryResult
    {
        return CoreHelper::clone($this->instance);
    }
}
