<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceList;
use VerizonLib\Models\ProfileChangeStateRequest;

/**
 * Builder for model ProfileChangeStateRequest
 *
 * @see ProfileChangeStateRequest
 */
class ProfileChangeStateRequestBuilder
{
    /**
     * @var ProfileChangeStateRequest
     */
    private $instance;

    private function __construct(ProfileChangeStateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Profile Change State Request Builder object.
     *
     * @param DeviceList[] $devices
     * @param string $accountName
     * @param string $smsrOid
     */
    public static function init(array $devices, string $accountName, string $smsrOid): self
    {
        return new self(new ProfileChangeStateRequest($devices, $accountName, $smsrOid));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Profile Change State Request object.
     */
    public function build(): ProfileChangeStateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
