<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\StatusResponse;
use VerizonLib\Models\Subrequest;

/**
 * Builder for model StatusResponse
 *
 * @see StatusResponse
 */
class StatusResponseBuilder
{
    /**
     * @var StatusResponse
     */
    private $instance;

    private function __construct(StatusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Status Response Builder object.
     */
    public static function init(): self
    {
        return new self(new StatusResponse());
    }

    /**
     * Sets request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets subrequests field.
     *
     * @param Subrequest[]|null $value
     */
    public function subrequests(?array $value): self
    {
        $this->instance->setSubrequests($value);
        return $this;
    }

    /**
     * Initializes a new Status Response object.
     */
    public function build(): StatusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
