/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of AppConfigResponse
 */
interface AppConfigResponse {
  /** The short summary of the error */
  error: string;
  /** The detailed description of the error */
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export class AppConfigResponseError extends ApiError<AppConfigResponse> {}
