<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;
use VerizonLib\ApiHelper;

/**
 * List of devices to removes.
 */
class V1ListOfLicensesToRemoveRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string[]
     */
    private $deviceList;

    /**
     * @param string[] $deviceList
     */
    public function __construct(array $deviceList)
    {
        $this->deviceList = $deviceList;
    }

    /**
     * Returns Type.
     * Set to 'append' to append the devices in the current request to the existing list. If there is no
     * existing list then it will be created with only these devices. Leave this parameter out when you
     * want to replace the existing list with the devices in the current request.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Set to 'append' to append the devices in the current request to the existing list. If there is no
     * existing list then it will be created with only these devices. Leave this parameter out when you
     * want to replace the existing list with the devices in the current request.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Device List.
     * The IMEIs of the devices.
     *
     * @return string[]
     */
    public function getDeviceList(): array
    {
        return $this->deviceList;
    }

    /**
     * Sets Device List.
     * The IMEIs of the devices.
     *
     * @required
     * @maps deviceList
     *
     * @param string[] $deviceList
     */
    public function setDeviceList(array $deviceList): void
    {
        $this->deviceList = $deviceList;
    }

    /**
     * Converts the V1ListOfLicensesToRemoveRequest object to a human-readable string representation.
     *
     * @return string The string representation of the V1ListOfLicensesToRemoveRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V1ListOfLicensesToRemoveRequest',
            [
                'type' => $this->type,
                'deviceList' => $this->deviceList,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['type', 'deviceList'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']   = $this->type;
        }
        $json['deviceList'] = $this->deviceList;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
