<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;
use VerizonLib\ApiHelper;

/**
 * Time window.
 */
class V3TimeWindow implements \JsonSerializable
{
    /**
     * @var int
     */
    private $startTime;

    /**
     * @var int
     */
    private $endTime;

    /**
     * @param int $startTime
     * @param int $endTime
     */
    public function __construct(int $startTime, int $endTime)
    {
        $this->startTime = $startTime;
        $this->endTime = $endTime;
    }

    /**
     * Returns Start Time.
     * Start hour in range [0..23], current hour >= startTime.
     */
    public function getStartTime(): int
    {
        return $this->startTime;
    }

    /**
     * Sets Start Time.
     * Start hour in range [0..23], current hour >= startTime.
     *
     * @required
     * @maps startTime
     */
    public function setStartTime(int $startTime): void
    {
        $this->startTime = $startTime;
    }

    /**
     * Returns End Time.
     * End hour in range [1..24], current hour < endTime.
     */
    public function getEndTime(): int
    {
        return $this->endTime;
    }

    /**
     * Sets End Time.
     * End hour in range [1..24], current hour < endTime.
     *
     * @required
     * @maps endTime
     */
    public function setEndTime(int $endTime): void
    {
        $this->endTime = $endTime;
    }

    /**
     * Converts the V3TimeWindow object to a human-readable string representation.
     *
     * @return string The string representation of the V3TimeWindow object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V3TimeWindow',
            [
                'startTime' => $this->startTime,
                'endTime' => $this->endTime,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['startTime', 'endTime'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['startTime'] = $this->startTime;
        $json['endTime']   = $this->endTime;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
