<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Cellphonenumber;

/**
 * Builder for model Cellphonenumber
 *
 * @see Cellphonenumber
 */
class CellphonenumberBuilder
{
    /**
     * @var Cellphonenumber
     */
    private $instance;

    private function __construct(Cellphonenumber $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cellphonenumber Builder object.
     */
    public static function init(): self
    {
        return new self(new Cellphonenumber());
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets carrier field.
     *
     * @param string|null $value
     */
    public function carrier(?string $value): self
    {
        $this->instance->setCarrier($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Cellphonenumber object.
     */
    public function build(): Cellphonenumber
    {
        return CoreHelper::clone($this->instance);
    }
}
