<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DataPercentage75TriggerAttribute;

/**
 * Builder for model DataPercentage75TriggerAttribute
 *
 * @see DataPercentage75TriggerAttribute
 */
class DataPercentage75TriggerAttributeBuilder
{
    /**
     * @var DataPercentage75TriggerAttribute
     */
    private $instance;

    private function __construct(DataPercentage75TriggerAttribute $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data Percentage 75 Trigger Attribute Builder object.
     */
    public static function init(): self
    {
        return new self(new DataPercentage75TriggerAttribute());
    }

    /**
     * Sets key field.
     *
     * @param string|null $value
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param bool|null $value
     */
    public function value(?bool $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Data Percentage 75 Trigger Attribute object.
     */
    public function build(): DataPercentage75TriggerAttribute
    {
        return CoreHelper::clone($this->instance);
    }
}
