<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\DeviceGroupUpdateRequest;
use VerizonLib\Models\DeviceId;

/**
 * Builder for model DeviceGroupUpdateRequest
 *
 * @see DeviceGroupUpdateRequest
 */
class DeviceGroupUpdateRequestBuilder
{
    /**
     * @var DeviceGroupUpdateRequest
     */
    private $instance;

    private function __construct(DeviceGroupUpdateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Group Update Request Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceGroupUpdateRequest());
    }

    /**
     * Sets devices To Add field.
     *
     * @param DeviceId[]|null $value
     */
    public function devicesToAdd(?array $value): self
    {
        $this->instance->setDevicesToAdd($value);
        return $this;
    }

    /**
     * Sets devices To Remove field.
     *
     * @param DeviceId[]|null $value
     */
    public function devicesToRemove(?array $value): self
    {
        $this->instance->setDevicesToRemove($value);
        return $this;
    }

    /**
     * Sets new Group Description field.
     *
     * @param string|null $value
     */
    public function newGroupDescription(?string $value): self
    {
        $this->instance->setNewGroupDescription($value);
        return $this;
    }

    /**
     * Sets new Group Name field.
     *
     * @param string|null $value
     */
    public function newGroupName(?string $value): self
    {
        $this->instance->setNewGroupName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device Group Update Request object.
     */
    public function build(): DeviceGroupUpdateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
