<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\Device;
use VerizonLib\Models\History;
use VerizonLib\Models\HistoryAttributeValue;

/**
 * Builder for model History
 *
 * @see History
 */
class HistoryBuilder
{
    /**
     * @var History
     */
    private $instance;

    private function __construct(History $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new History Builder object.
     *
     * @param string $accountName
     * @param Device $device
     */
    public static function init(string $accountName, Device $device): self
    {
        return new self(new History($accountName, $device));
    }

    /**
     * Sets attributes field.
     *
     * @param HistoryAttributeValue|null $value
     */
    public function attributes(?HistoryAttributeValue $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new History object.
     */
    public function build(): History
    {
        return CoreHelper::clone($this->instance);
    }
}
