<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models\Builders;

use Core\Utils\CoreHelper;
use VerizonLib\Models\GroupName;
use VerizonLib\Models\M5GBiaccountNameobject;
use VerizonLib\Models\M5GBiCarrierInformation;
use VerizonLib\Models\M5GBideviceId1;
use VerizonLib\Models\M5GBikeyValue1;

/**
 * Builder for model M5GBiaccountNameobject
 *
 * @see M5GBiaccountNameobject
 */
class M5GBiaccountNameobjectBuilder
{
    /**
     * @var M5GBiaccountNameobject
     */
    private $instance;

    private function __construct(M5GBiaccountNameobject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new M5 G Biaccount Nameobject Builder object.
     */
    public static function init(): self
    {
        return new self(new M5GBiaccountNameobject());
    }

    /**
     * Sets account Name field.
     *
     * @param string|null $value
     */
    public function accountName(?string $value): self
    {
        $this->instance->setAccountName($value);
        return $this;
    }

    /**
     * Sets billing Cycle End Date field.
     *
     * @param string|null $value
     */
    public function billingCycleEndDate(?string $value): self
    {
        $this->instance->setBillingCycleEndDate($value);
        return $this;
    }

    /**
     * Sets carrier Information field.
     *
     * @param M5GBiCarrierInformation[]|null $value
     */
    public function carrierInformation(?array $value): self
    {
        $this->instance->setCarrierInformation($value);
        return $this;
    }

    /**
     * Sets connected field.
     *
     * @param bool|null $value
     */
    public function connected(?bool $value): self
    {
        $this->instance->setConnected($value);
        return $this;
    }

    /**
     * Sets created At field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets custom Fields field.
     *
     * @param M5GBikeyValue1[]|null $value
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets device Ids field.
     *
     * @param M5GBideviceId1[]|null $value
     */
    public function deviceIds(?array $value): self
    {
        $this->instance->setDeviceIds($value);
        return $this;
    }

    /**
     * Sets extended Attributes field.
     *
     * @param M5GBikeyValue1[]|null $value
     */
    public function extendedAttributes(?array $value): self
    {
        $this->instance->setExtendedAttributes($value);
        return $this;
    }

    /**
     * Sets group Names field.
     *
     * @param GroupName[]|null $value
     */
    public function groupNames(?array $value): self
    {
        $this->instance->setGroupNames($value);
        return $this;
    }

    /**
     * Sets ip Address field.
     *
     * @param string|null $value
     */
    public function ipaddress(?string $value): self
    {
        $this->instance->setIpaddress($value);
        return $this;
    }

    /**
     * Sets last Activation By field.
     *
     * @param string|null $value
     */
    public function lastActivationBy(?string $value): self
    {
        $this->instance->setLastActivationBy($value);
        return $this;
    }

    /**
     * Sets last Activation Date field.
     *
     * @param string|null $value
     */
    public function lastActivationDate(?string $value): self
    {
        $this->instance->setLastActivationDate($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new M5 G Biaccount Nameobject object.
     */
    public function build(): M5GBiaccountNameobject
    {
        return CoreHelper::clone($this->instance);
    }
}
