/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of WnpRestErrorResponse
 */
interface WnpRestErrorResponse {
  /** Rest error response. */
  errorCode?: string;
  /** Error message details. */
  errorMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export class WnpRestErrorResponseError extends ApiError<WnpRestErrorResponse> {}
