# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class Gatewayidentifier(object):

    """Implementation of the 'Gatewayidentifier' model.

    Attributes:
        deviceid (str): a unique parent deviceid used to group all Lora
            sensors. Sensors need parent gateway for connection
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "deviceid": 'deviceid'
    }

    _optionals = [
        'deviceid',
    ]

    def __init__(self,
                 deviceid=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the Gatewayidentifier class"""

        # Initialize members of the class
        if deviceid is not APIHelper.SKIP:
            self.deviceid = deviceid 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        deviceid = dictionary.get("deviceid") if dictionary.get("deviceid") else APIHelper.SKIP
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(deviceid,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'deviceid={(self.deviceid if hasattr(self, "deviceid") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'deviceid={(self.deviceid if hasattr(self, "deviceid") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
