/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CampaignMetaInfoProtocol
 */
export enum CampaignMetaInfoProtocol {
  LwM2M = 'LWM2M',
  Omddm = 'OMD-DM',
}

/**
 * Schema for CampaignMetaInfoProtocol
 */
export const campaignMetaInfoProtocolSchema: Schema<CampaignMetaInfoProtocol> = stringEnum(
  CampaignMetaInfoProtocol
);
