/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** The service plan code to switch to */
export interface ChangePlanDetails {
  toCarrierServicePlanCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const changePlanDetailsSchema: Schema<ChangePlanDetails> = typedExpandoObject(
  {
    toCarrierServicePlanCode: ['toCarrierServicePlanCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
