/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  DtoResourceidentifier,
  dtoResourceidentifierSchema,
} from './dtoResourceidentifier';
import { Rbstiltconfig, rbstiltconfigSchema } from './rbstiltconfig';

export interface DtoDeviceCommand {
  /** The numeric account name, which must include leading zeros */
  accountName?: string;
  configuration?: Rbstiltconfig;
  resourceidentifier?: DtoResourceidentifier;
  additionalProperties?: Record<string, unknown>;
}

export const dtoDeviceCommandSchema: Schema<DtoDeviceCommand> = typedExpandoObject(
  {
    accountName: ['accountName', optional(string())],
    configuration: ['configuration', optional(lazy(() => rbstiltconfigSchema))],
    resourceidentifier: [
      'resourceidentifier',
      optional(lazy(() => dtoResourceidentifierSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
