/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  DtoResourceidentifier,
  dtoResourceidentifierSchema,
} from './dtoResourceidentifier';
import { ResourceRule, resourceRuleSchema } from './resourceRule';

export interface DtoOverwriteRuleRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  resourceidentifier?: DtoResourceidentifier;
  rule?: ResourceRule;
}

export const dtoOverwriteRuleRequestSchema: Schema<DtoOverwriteRuleRequest> = object(
  {
    accountname: ['accountname', optional(string())],
    resourceidentifier: [
      'resourceidentifier',
      optional(lazy(() => dtoResourceidentifierSchema)),
    ],
    rule: ['rule', optional(lazy(() => resourceRuleSchema))],
  }
);
