/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Cancelation status. */
export interface FotaV3SuccessResult {
  /** True or false. */
  success: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const fotaV3SuccessResultSchema: Schema<FotaV3SuccessResult> = typedExpandoObject(
  { success: ['success', boolean()] },
  'additionalProperties',
  optional(unknown())
);
