/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Request to end a Connectivity Management session. */
export interface LogOutRequest {
  /** The session token is returned to confirm that it was invalidated. */
  sessionToken?: string;
  additionalProperties?: Record<string, unknown>;
}

export const logOutRequestSchema: Schema<LogOutRequest> = typedExpandoObject(
  { sessionToken: ['sessionToken', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
