/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface M5GBikeyValue1 {
  key?: string;
  value?: string;
  additionalProperties?: Record<string, unknown>;
}

export const m5GBikeyValue1Schema: Schema<M5GBikeyValue1> = typedExpandoObject(
  { key: ['key', optional(string())], value: ['value', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
