/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** List of the field names and values to set. */
export interface MConfiguration {
  frequency?: string;
  additionalProperties?: Record<string, unknown>;
}

export const mConfigurationSchema: Schema<MConfiguration> = typedExpandoObject(
  { frequency: ['frequency', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
