/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  MecPlatformsAdditionalSupportInfoData,
  mecPlatformsAdditionalSupportInfoDataSchema,
} from './mecPlatformsAdditionalSupportInfoData';

/** Additional service support information for the MEC platform. */
export interface MecPlatformsAdditionalSupportInfo {
  /** Type of additional service support information for the MEC platform. */
  type?: string;
  /** Data about additional service support information for the MEC platform. */
  data?: MecPlatformsAdditionalSupportInfoData;
}

export const mecPlatformsAdditionalSupportInfoSchema: Schema<MecPlatformsAdditionalSupportInfo> = object(
  {
    type: ['type', optional(string())],
    data: [
      'data',
      optional(lazy(() => mecPlatformsAdditionalSupportInfoDataSchema)),
    ],
  }
);
