/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { Address, addressSchema } from './address';
import { CustomerName, customerNameSchema } from './customerName';

/** The customer name and the address of the device's primary place of use. Leave these fields empty to use the account profile address as the primary place of use. These values will be applied to all devices in the request.If the account is enabled for non-geographic MDNs and the device supports it, the primaryPlaceOfUse address will also be used to derive the MDN for the device. */
export interface PlaceOfUse {
  /** The customer address for the line's primary place of use, for line usage taxation. */
  address: Address;
  /** The customer name to be used for line usage taxation. */
  customerName: CustomerName;
  additionalProperties?: Record<string, unknown>;
}

export const placeOfUseSchema: Schema<PlaceOfUse> = typedExpandoObject(
  {
    address: ['address', lazy(() => addressSchema)],
    customerName: ['customerName', lazy(() => customerNameSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
