/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import {
  RateplanRatePlanGroup,
  rateplanRatePlanGroupSchema,
} from './containers/rateplanRatePlanGroup';

export interface Rateplan {
  /** An array of rate plan group names */
  ratePlanGroup?: RateplanRatePlanGroup[];
  additionalProperties?: Record<string, unknown>;
}

export const rateplanSchema: Schema<Rateplan> = typedExpandoObject(
  {
    ratePlanGroup: [
      'ratePlanGroup',
      optional(array(rateplanRatePlanGroupSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
