/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema';

export interface SaeAlert {
  /**
   * The ITIS Code that describes the alert/danger/hazard. All ITS standards use the same types here to explain the type of the alert/danger/hazard involved.
   * The complete set of ITIS codes can be found in Volume Two of the SAE J2540 standard. This is a set of over 1000 items which are used to encode common events and list items in ITS.
   */
  typeEvent: number;
  /** ITIS code set entries to further describe the event, give advice, or any other ITIS codes related to the event/danger/hazard. */
  description?: number[];
}

export const saeAlertSchema: Schema<SaeAlert> = object({
  typeEvent: ['typeEvent', number()],
  description: ['description', optional(array(number()))],
});
