/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Unit
 */
export enum Unit {
  Minutes = 'minutes',
  Hours = 'hours',
}

/**
 * Schema for Unit
 */
export const unitSchema: Schema<Unit> = stringEnum(Unit);
