/*
Package verizon

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// V2LicenseDevice represents a V2LicenseDevice struct.
// Device IMEI list.
type V2LicenseDevice struct {
    // Device IMEI.
    DeviceId             string                 `json:"deviceId"`
    // License assignment time.
    AssignmentTime       *string                `json:"assignmentTime,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for V2LicenseDevice,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v V2LicenseDevice) String() string {
    return fmt.Sprintf(
    	"V2LicenseDevice[DeviceId=%v, AssignmentTime=%v, AdditionalProperties=%v]",
    	v.DeviceId, v.AssignmentTime, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for V2LicenseDevice.
// It customizes the JSON marshaling process for V2LicenseDevice objects.
func (v V2LicenseDevice) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "deviceId", "assignmentTime"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the V2LicenseDevice object to a map representation for JSON marshaling.
func (v V2LicenseDevice) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    structMap["deviceId"] = v.DeviceId
    if v.AssignmentTime != nil {
        structMap["assignmentTime"] = v.AssignmentTime
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for V2LicenseDevice.
// It customizes the JSON unmarshaling process for V2LicenseDevice objects.
func (v *V2LicenseDevice) UnmarshalJSON(input []byte) error {
    var temp tempV2LicenseDevice
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "deviceId", "assignmentTime")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.DeviceId = *temp.DeviceId
    v.AssignmentTime = temp.AssignmentTime
    return nil
}

// tempV2LicenseDevice is a temporary struct used for validating the fields of V2LicenseDevice.
type tempV2LicenseDevice  struct {
    DeviceId       *string `json:"deviceId"`
    AssignmentTime *string `json:"assignmentTime,omitempty"`
}

func (v *tempV2LicenseDevice) validate() error {
    var errs []string
    if v.DeviceId == nil {
        errs = append(errs, "required field `deviceId` is missing for type `V2LicenseDevice`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
