<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;
use VerizonLib\ApiHelper;

/**
 * Contains usage information per device.
 */
class AggregateUsageItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $imei;

    /**
     * @var int|null
     */
    private $numberOfSessions;

    /**
     * @var int|null
     */
    private $bytesTransferred;

    /**
     * Returns Imei.
     * International Mobile Equipment Identifier. This is the ID of the device reporting usage.
     */
    public function getImei(): ?string
    {
        return $this->imei;
    }

    /**
     * Sets Imei.
     * International Mobile Equipment Identifier. This is the ID of the device reporting usage.
     *
     * @maps imei
     */
    public function setImei(?string $imei): void
    {
        $this->imei = $imei;
    }

    /**
     * Returns Number of Sessions.
     * Number of sessions established by the device reporting usage.
     */
    public function getNumberOfSessions(): ?int
    {
        return $this->numberOfSessions;
    }

    /**
     * Sets Number of Sessions.
     * Number of sessions established by the device reporting usage.
     *
     * @maps numberOfSessions
     */
    public function setNumberOfSessions(?int $numberOfSessions): void
    {
        $this->numberOfSessions = $numberOfSessions;
    }

    /**
     * Returns Bytes Transferred.
     * The amount of data transferred by the device reporting usage, measured in Bytes.
     */
    public function getBytesTransferred(): ?int
    {
        return $this->bytesTransferred;
    }

    /**
     * Sets Bytes Transferred.
     * The amount of data transferred by the device reporting usage, measured in Bytes.
     *
     * @maps bytesTransferred
     */
    public function setBytesTransferred(?int $bytesTransferred): void
    {
        $this->bytesTransferred = $bytesTransferred;
    }

    /**
     * Converts the AggregateUsageItem object to a human-readable string representation.
     *
     * @return string The string representation of the AggregateUsageItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AggregateUsageItem',
            [
                'imei' => $this->imei,
                'numberOfSessions' => $this->numberOfSessions,
                'bytesTransferred' => $this->bytesTransferred,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['imei', 'numberOfSessions', 'bytesTransferred'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->imei)) {
            $json['imei']             = $this->imei;
        }
        if (isset($this->numberOfSessions)) {
            $json['numberOfSessions'] = $this->numberOfSessions;
        }
        if (isset($this->bytesTransferred)) {
            $json['bytesTransferred'] = $this->bytesTransferred;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
