<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;
use VerizonLib\ApiHelper;

class ManagedAccountsProvisionResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $txid;

    /**
     * @var string|null
     */
    private $accountName;

    /**
     * @var string|null
     */
    private $paccountName;

    /**
     * @var string|null
     */
    private $serviceName = ServiceName::LOCATION;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $reason;

    /**
     * Returns Txid.
     * Transaction identifier
     */
    public function getTxid(): ?string
    {
        return $this->txid;
    }

    /**
     * Sets Txid.
     * Transaction identifier
     *
     * @maps txid
     */
    public function setTxid(?string $txid): void
    {
        $this->txid = $txid;
    }

    /**
     * Returns Account Name.
     * Account identifier
     */
    public function getAccountName(): ?string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     * Account identifier
     *
     * @maps accountName
     */
    public function setAccountName(?string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Paccount Name.
     * Primary Account identifier
     */
    public function getPaccountName(): ?string
    {
        return $this->paccountName;
    }

    /**
     * Sets Paccount Name.
     * Primary Account identifier
     *
     * @maps paccountName
     */
    public function setPaccountName(?string $paccountName): void
    {
        $this->paccountName = $paccountName;
    }

    /**
     * Returns Service Name.
     * Service name
     */
    public function getServiceName(): ?string
    {
        return $this->serviceName;
    }

    /**
     * Sets Service Name.
     * Service name
     *
     * @maps serviceName
     * @factory \VerizonLib\Models\ServiceName::checkValue
     */
    public function setServiceName(?string $serviceName): void
    {
        $this->serviceName = $serviceName;
    }

    /**
     * Returns Status.
     * Provision status. Success or Fail
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Provision status. Success or Fail
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Reason.
     * Detailed reason
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * Detailed reason
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Converts the ManagedAccountsProvisionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ManagedAccountsProvisionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ManagedAccountsProvisionResponse',
            [
                'txid' => $this->txid,
                'accountName' => $this->accountName,
                'paccountName' => $this->paccountName,
                'serviceName' => $this->serviceName,
                'status' => $this->status,
                'reason' => $this->reason,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['txid', 'accountName', 'paccountName', 'serviceName', 'status', 'reason'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->txid)) {
            $json['txid']         = $this->txid;
        }
        if (isset($this->accountName)) {
            $json['accountName']  = $this->accountName;
        }
        if (isset($this->paccountName)) {
            $json['paccountName'] = $this->paccountName;
        }
        if (isset($this->serviceName)) {
            $json['serviceName']  = ServiceName::checkValue($this->serviceName);
        }
        if (isset($this->status)) {
            $json['status']       = $this->status;
        }
        if (isset($this->reason)) {
            $json['reason']       = $this->reason;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
