/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ConnectivityManagementSuccessResult type.
 */
public class ConnectivityManagementSuccessResult {
    private Boolean success;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ConnectivityManagementSuccessResult() {
    }

    /**
     * Initialization constructor.
     * @param  success  Boolean value for success.
     */
    public ConnectivityManagementSuccessResult(
            Boolean success) {
        this.success = success;
    }

    /**
     * Getter for Success.
     * A value of “true” indicates that the device group was created successfully.
     * @return Returns the Boolean
     */
    @JsonGetter("success")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * A value of “true” indicates that the device group was created successfully.
     * @param success Value for Boolean
     */
    @JsonSetter("success")
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ConnectivityManagementSuccessResult into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConnectivityManagementSuccessResult [" + "success=" + success
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ConnectivityManagementSuccessResult.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConnectivityManagementSuccessResult.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .success(getSuccess());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ConnectivityManagementSuccessResult}.
     */
    public static class Builder {
        private Boolean success;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for success.
         * @param  success  Boolean value for success.
         * @return Builder
         */
        public Builder success(Boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ConnectivityManagementSuccessResult} object using the set fields.
         * @return {@link ConnectivityManagementSuccessResult}
         */
        public ConnectivityManagementSuccessResult build() {
            ConnectivityManagementSuccessResult model =
                    new ConnectivityManagementSuccessResult(success);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
