/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ConnectionResponse type.
 */
public class ConnectionResponse {
    private String mqttUrl;

    /**
     * Default constructor.
     */
    public ConnectionResponse() {
    }

    /**
     * Initialization constructor.
     * @param  mqttUrl  String value for mqttUrl.
     */
    public ConnectionResponse(
            String mqttUrl) {
        this.mqttUrl = mqttUrl;
    }

    /**
     * Getter for MqttUrl.
     * @return Returns the String
     */
    @JsonGetter("MqttURL")
    public String getMqttUrl() {
        return mqttUrl;
    }

    /**
     * Setter for MqttUrl.
     * @param mqttUrl Value for String
     */
    @JsonSetter("MqttURL")
    public void setMqttUrl(String mqttUrl) {
        this.mqttUrl = mqttUrl;
    }

    /**
     * Converts this ConnectionResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConnectionResponse [" + "mqttUrl=" + mqttUrl + "]";
    }

    /**
     * Builds a new {@link ConnectionResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConnectionResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(mqttUrl);
        return builder;
    }

    /**
     * Class to build instances of {@link ConnectionResponse}.
     */
    public static class Builder {
        private String mqttUrl;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  mqttUrl  String value for mqttUrl.
         */
        public Builder(String mqttUrl) {
            this.mqttUrl = mqttUrl;
        }

        /**
         * Setter for mqttUrl.
         * @param  mqttUrl  String value for mqttUrl.
         * @return Builder
         */
        public Builder mqttUrl(String mqttUrl) {
            this.mqttUrl = mqttUrl;
            return this;
        }

        /**
         * Builds a new {@link ConnectionResponse} object using the set fields.
         * @return {@link ConnectionResponse}
         */
        public ConnectionResponse build() {
            return new ConnectionResponse(mqttUrl);
        }
    }
}
