/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for NodeOffsetPointLl type.
 */
public class NodeOffsetPointLl {
    private NodeLLmD64B nodeLatLon;

    /**
     * Default constructor.
     */
    public NodeOffsetPointLl() {
    }

    /**
     * Initialization constructor.
     * @param  nodeLatLon  NodeLLmD64B value for nodeLatLon.
     */
    public NodeOffsetPointLl(
            NodeLLmD64B nodeLatLon) {
        this.nodeLatLon = nodeLatLon;
    }

    /**
     * Getter for NodeLatLon.
     * A 64-bit node type with lat-long values expressed in standard SAE 1/10th of a microdegree.
     * @return Returns the NodeLLmD64B
     */
    @JsonGetter("nodeLatLon")
    public NodeLLmD64B getNodeLatLon() {
        return nodeLatLon;
    }

    /**
     * Setter for NodeLatLon.
     * A 64-bit node type with lat-long values expressed in standard SAE 1/10th of a microdegree.
     * @param nodeLatLon Value for NodeLLmD64B
     */
    @JsonSetter("nodeLatLon")
    public void setNodeLatLon(NodeLLmD64B nodeLatLon) {
        this.nodeLatLon = nodeLatLon;
    }

    /**
     * Converts this NodeOffsetPointLl into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NodeOffsetPointLl [" + "nodeLatLon=" + nodeLatLon + "]";
    }

    /**
     * Builds a new {@link NodeOffsetPointLl.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NodeOffsetPointLl.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(nodeLatLon);
        return builder;
    }

    /**
     * Class to build instances of {@link NodeOffsetPointLl}.
     */
    public static class Builder {
        private NodeLLmD64B nodeLatLon;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  nodeLatLon  NodeLLmD64B value for nodeLatLon.
         */
        public Builder(NodeLLmD64B nodeLatLon) {
            this.nodeLatLon = nodeLatLon;
        }

        /**
         * Setter for nodeLatLon.
         * @param  nodeLatLon  NodeLLmD64B value for nodeLatLon.
         * @return Builder
         */
        public Builder nodeLatLon(NodeLLmD64B nodeLatLon) {
            this.nodeLatLon = nodeLatLon;
            return this;
        }

        /**
         * Builds a new {@link NodeOffsetPointLl} object using the set fields.
         * @return {@link NodeOffsetPointLl}
         */
        public NodeOffsetPointLl build() {
            return new NodeOffsetPointLl(nodeLatLon);
        }
    }
}
