/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProvisioningHistory type.
 */
public class ProvisioningHistory {
    private String occurredAt;
    private String status;
    private String eventBy;
    private String eventType;
    private String mdn;
    private String msisdn;
    private String servicePlan;
    private List<CustomFields> extendedAttributes;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProvisioningHistory() {
    }

    /**
     * Initialization constructor.
     * @param  occurredAt  String value for occurredAt.
     * @param  status  String value for status.
     * @param  eventBy  String value for eventBy.
     * @param  eventType  String value for eventType.
     * @param  mdn  String value for mdn.
     * @param  msisdn  String value for msisdn.
     * @param  servicePlan  String value for servicePlan.
     * @param  extendedAttributes  List of CustomFields value for extendedAttributes.
     */
    public ProvisioningHistory(
            String occurredAt,
            String status,
            String eventBy,
            String eventType,
            String mdn,
            String msisdn,
            String servicePlan,
            List<CustomFields> extendedAttributes) {
        this.occurredAt = occurredAt;
        this.status = status;
        this.eventBy = eventBy;
        this.eventType = eventType;
        this.mdn = mdn;
        this.msisdn = msisdn;
        this.servicePlan = servicePlan;
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Getter for OccurredAt.
     * The date and time when the provisioning event occured.
     * @return Returns the String
     */
    @JsonGetter("occurredAt")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOccurredAt() {
        return occurredAt;
    }

    /**
     * Setter for OccurredAt.
     * The date and time when the provisioning event occured.
     * @param occurredAt Value for String
     */
    @JsonSetter("occurredAt")
    public void setOccurredAt(String occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for Status.
     * The success or failure of the provisioning event.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * The success or failure of the provisioning event.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for EventBy.
     * The user who performed the provisioning event.
     * @return Returns the String
     */
    @JsonGetter("eventBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEventBy() {
        return eventBy;
    }

    /**
     * Setter for EventBy.
     * The user who performed the provisioning event.
     * @param eventBy Value for String
     */
    @JsonSetter("eventBy")
    public void setEventBy(String eventBy) {
        this.eventBy = eventBy;
    }

    /**
     * Getter for EventType.
     * The provisioning action:Activate,Suspend,Restore,Deactivate,Device Move.
     * @return Returns the String
     */
    @JsonGetter("eventType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEventType() {
        return eventType;
    }

    /**
     * Setter for EventType.
     * The provisioning action:Activate,Suspend,Restore,Deactivate,Device Move.
     * @param eventType Value for String
     */
    @JsonSetter("eventType")
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * Getter for Mdn.
     * The MDN assigned to the device after the provisioning event.
     * @return Returns the String
     */
    @JsonGetter("mdn")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMdn() {
        return mdn;
    }

    /**
     * Setter for Mdn.
     * The MDN assigned to the device after the provisioning event.
     * @param mdn Value for String
     */
    @JsonSetter("mdn")
    public void setMdn(String mdn) {
        this.mdn = mdn;
    }

    /**
     * Getter for Msisdn.
     * The MSISDN assigned to the device after the provisioning event.
     * @return Returns the String
     */
    @JsonGetter("msisdn")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Setter for Msisdn.
     * The MSISDN assigned to the device after the provisioning event.
     * @param msisdn Value for String
     */
    @JsonSetter("msisdn")
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    /**
     * Getter for ServicePlan.
     * The service plan of the device after the provisioning event occurred.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * The service plan of the device after the provisioning event occurred.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for ExtendedAttributes.
     * Any extended attributes for the event, as Key and Value pairs.
     * @return Returns the List of CustomFields
     */
    @JsonGetter("extendedAttributes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CustomFields> getExtendedAttributes() {
        return extendedAttributes;
    }

    /**
     * Setter for ExtendedAttributes.
     * Any extended attributes for the event, as Key and Value pairs.
     * @param extendedAttributes Value for List of CustomFields
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes(List<CustomFields> extendedAttributes) {
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProvisioningHistory into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProvisioningHistory [" + "occurredAt=" + occurredAt + ", status=" + status
                + ", eventBy=" + eventBy + ", eventType=" + eventType + ", mdn=" + mdn + ", msisdn="
                + msisdn + ", servicePlan=" + servicePlan + ", extendedAttributes="
                + extendedAttributes + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProvisioningHistory.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProvisioningHistory.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .occurredAt(getOccurredAt())
                .status(getStatus())
                .eventBy(getEventBy())
                .eventType(getEventType())
                .mdn(getMdn())
                .msisdn(getMsisdn())
                .servicePlan(getServicePlan())
                .extendedAttributes(getExtendedAttributes());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProvisioningHistory}.
     */
    public static class Builder {
        private String occurredAt;
        private String status;
        private String eventBy;
        private String eventType;
        private String mdn;
        private String msisdn;
        private String servicePlan;
        private List<CustomFields> extendedAttributes;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for occurredAt.
         * @param  occurredAt  String value for occurredAt.
         * @return Builder
         */
        public Builder occurredAt(String occurredAt) {
            this.occurredAt = occurredAt;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for eventBy.
         * @param  eventBy  String value for eventBy.
         * @return Builder
         */
        public Builder eventBy(String eventBy) {
            this.eventBy = eventBy;
            return this;
        }

        /**
         * Setter for eventType.
         * @param  eventType  String value for eventType.
         * @return Builder
         */
        public Builder eventType(String eventType) {
            this.eventType = eventType;
            return this;
        }

        /**
         * Setter for mdn.
         * @param  mdn  String value for mdn.
         * @return Builder
         */
        public Builder mdn(String mdn) {
            this.mdn = mdn;
            return this;
        }

        /**
         * Setter for msisdn.
         * @param  msisdn  String value for msisdn.
         * @return Builder
         */
        public Builder msisdn(String msisdn) {
            this.msisdn = msisdn;
            return this;
        }

        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Setter for extendedAttributes.
         * @param  extendedAttributes  List of CustomFields value for extendedAttributes.
         * @return Builder
         */
        public Builder extendedAttributes(List<CustomFields> extendedAttributes) {
            this.extendedAttributes = extendedAttributes;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProvisioningHistory} object using the set fields.
         * @return {@link ProvisioningHistory}
         */
        public ProvisioningHistory build() {
            ProvisioningHistory model =
                    new ProvisioningHistory(occurredAt, status, eventBy, eventType, mdn, msisdn,
                            servicePlan, extendedAttributes);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
