/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RoadSignId type.
 */
public class RoadSignId {
    private Position position;
    private String viewAngle;

    /**
     * Default constructor.
     */
    public RoadSignId() {
    }

    /**
     * Initialization constructor.
     * @param  position  Position value for position.
     * @param  viewAngle  String value for viewAngle.
     */
    public RoadSignId(
            Position position,
            String viewAngle) {
        this.position = position;
        this.viewAngle = viewAngle;
    }

    /**
     * Getter for Position.
     * It provides a precise location in the WGS-84 coordinate system, from which short offsets may
     * be used to create additional data using a flat earth projection centered on this location.
     * @return Returns the Position
     */
    @JsonGetter("position")
    public Position getPosition() {
        return position;
    }

    /**
     * Setter for Position.
     * It provides a precise location in the WGS-84 coordinate system, from which short offsets may
     * be used to create additional data using a flat earth projection centered on this location.
     * @param position Value for Position
     */
    @JsonSetter("position")
    public void setPosition(Position position) {
        this.position = position;
    }

    /**
     * Getter for ViewAngle.
     * @return Returns the String
     */
    @JsonGetter("viewAngle")
    public String getViewAngle() {
        return viewAngle;
    }

    /**
     * Setter for ViewAngle.
     * @param viewAngle Value for String
     */
    @JsonSetter("viewAngle")
    public void setViewAngle(String viewAngle) {
        this.viewAngle = viewAngle;
    }

    /**
     * Converts this RoadSignId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RoadSignId [" + "position=" + position + ", viewAngle=" + viewAngle + "]";
    }

    /**
     * Builds a new {@link RoadSignId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RoadSignId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(position, viewAngle);
        return builder;
    }

    /**
     * Class to build instances of {@link RoadSignId}.
     */
    public static class Builder {
        private Position position;
        private String viewAngle;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  position  Position value for position.
         * @param  viewAngle  String value for viewAngle.
         */
        public Builder(Position position, String viewAngle) {
            this.position = position;
            this.viewAngle = viewAngle;
        }

        /**
         * Setter for position.
         * @param  position  Position value for position.
         * @return Builder
         */
        public Builder position(Position position) {
            this.position = position;
            return this;
        }

        /**
         * Setter for viewAngle.
         * @param  viewAngle  String value for viewAngle.
         * @return Builder
         */
        public Builder viewAngle(String viewAngle) {
            this.viewAngle = viewAngle;
            return this;
        }

        /**
         * Builds a new {@link RoadSignId} object using the set fields.
         * @return {@link RoadSignId}
         */
        public RoadSignId build() {
            return new RoadSignId(position, viewAngle);
        }
    }
}
