/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * RulesCycleType to be used.
 */
public enum RulesCycleType {
    DAILY,

    WEEKLY,

    MONTHLY;


    private static TreeMap<String, RulesCycleType> valueMap = new TreeMap<>();
    private String value;

    static {
        DAILY.value = "Daily";
        WEEKLY.value = "Weekly";
        MONTHLY.value = "Monthly";

        valueMap.put("Daily", DAILY);
        valueMap.put("Weekly", WEEKLY);
        valueMap.put("Monthly", MONTHLY);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static RulesCycleType constructFromString(String toConvert) throws IOException {
        RulesCycleType enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static RulesCycleType fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RulesCycleType values to list of string values.
     * @param toConvert The list of RulesCycleType values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<RulesCycleType> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (RulesCycleType enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 