/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for V1ListOfLicensesToRemoveRequest type.
 */
public class V1ListOfLicensesToRemoveRequest {
    private String type;
    private List<String> deviceList;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public V1ListOfLicensesToRemoveRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deviceList  List of String value for deviceList.
     * @param  type  String value for type.
     */
    public V1ListOfLicensesToRemoveRequest(
            List<String> deviceList,
            String type) {
        this.type = type;
        this.deviceList = deviceList;
    }

    /**
     * Getter for Type.
     * Set to 'append' to append the devices in the current request to the existing list. If there
     * is no existing list then it will be created with only these devices. Leave this parameter out
     * when you want to replace the existing list with the devices in the current request.
     * @return Returns the String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Set to 'append' to append the devices in the current request to the existing list. If there
     * is no existing list then it will be created with only these devices. Leave this parameter out
     * when you want to replace the existing list with the devices in the current request.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for DeviceList.
     * The IMEIs of the devices.
     * @return Returns the List of String
     */
    @JsonGetter("deviceList")
    public List<String> getDeviceList() {
        return deviceList;
    }

    /**
     * Setter for DeviceList.
     * The IMEIs of the devices.
     * @param deviceList Value for List of String
     */
    @JsonSetter("deviceList")
    public void setDeviceList(List<String> deviceList) {
        this.deviceList = deviceList;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this V1ListOfLicensesToRemoveRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "V1ListOfLicensesToRemoveRequest [" + "deviceList=" + deviceList + ", type=" + type
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link V1ListOfLicensesToRemoveRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link V1ListOfLicensesToRemoveRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deviceList)
                .type(getType());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link V1ListOfLicensesToRemoveRequest}.
     */
    public static class Builder {
        private List<String> deviceList;
        private String type;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deviceList  List of String value for deviceList.
         */
        public Builder(List<String> deviceList) {
            this.deviceList = deviceList;
        }

        /**
         * Setter for deviceList.
         * @param  deviceList  List of String value for deviceList.
         * @return Builder
         */
        public Builder deviceList(List<String> deviceList) {
            this.deviceList = deviceList;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link V1ListOfLicensesToRemoveRequest} object using the set fields.
         * @return {@link V1ListOfLicensesToRemoveRequest}
         */
        public V1ListOfLicensesToRemoveRequest build() {
            V1ListOfLicensesToRemoveRequest model =
                    new V1ListOfLicensesToRemoveRequest(deviceList, type);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
